# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  revanced-cli = {
    pname = "revanced-cli";
    version = "2.10.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-cli/releases/download/v2.10.1/revanced-cli-2.10.1-all.jar";
      sha256 = "sha256-iG6PUvM2q96TT6AgzX7drNLsA6dc5cWRNinn3sPJPSA=";
    };
  };
  revanced-integrations = {
    pname = "revanced-integrations";
    version = "v0.36.6";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-integrations/releases/download/v0.36.6/app-release-unsigned.apk";
      sha256 = "sha256-1dLlw1ehb/rA5sqcxUX8qnXFIgyDMGHh3XniC+lvPts=";
    };
  };
  revanced-patches = {
    pname = "revanced-patches";
    version = "2.52.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-patches/releases/download/v2.52.1/revanced-patches-2.52.1.jar";
      sha256 = "sha256-ij0sqDSBqCo6sDVLDraaINvKgZcq/xy/GVt8WYmYfiU=";
    };
  };
}
