# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  revanced-cli = {
    pname = "revanced-cli";
    version = "2.11.2";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-cli/releases/download/v2.11.2/revanced-cli-2.11.2-all.jar";
      sha256 = "sha256-L50y/IogbB+qiv9yg8QTQCYW0gPoDaWpFXpTxPZUlf4=";
    };
  };
  revanced-integrations = {
    pname = "revanced-integrations";
    version = "v0.42.1";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-integrations/releases/download/v0.42.1/app-release-unsigned.apk";
      sha256 = "sha256-qVyTxGPyyj6QhObjUOmwa7jF7is+tf3WtDtY8cHS4VY=";
    };
  };
  revanced-patches = {
    pname = "revanced-patches";
    version = "2.69.0";
    src = fetchurl {
      url = "https://github.com/revanced/revanced-patches/releases/download/v2.69.0/revanced-patches-2.69.0.jar";
      sha256 = "sha256-AbfFachgNYTOE2XEF/1D0MYQVYOEa+HfG6ZyhXIjguM=";
    };
  };
}
